# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'range.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qtpy import QtCore, QtWidgets


class Ui_range_dialog(object):
    def setupUi(self, range_dialog):
        range_dialog.setObjectName("range_dialog")
        range_dialog.resize(531, 133)
        self.buttonBox = QtWidgets.QDialogButtonBox(range_dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 80, 471, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok
        )
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(range_dialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 66, 21))
        self.label.setObjectName("label")
        self.range_edit = QtWidgets.QLineEdit(range_dialog)
        self.range_edit.setGeometry(QtCore.QRect(110, 20, 391, 41))
        self.range_edit.setObjectName("range_edit")

        self.retranslateUi(range_dialog)
        self.buttonBox.accepted.connect(range_dialog.accept)  # type: ignore
        self.buttonBox.rejected.connect(range_dialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(range_dialog)

    def retranslateUi(self, range_dialog):
        _translate = QtCore.QCoreApplication.translate
        range_dialog.setWindowTitle(_translate("range_dialog", "Add scans by numbers"))
        self.label.setText(_translate("range_dialog", "Scan list:"))
        self.range_edit.setToolTip(
            _translate(
                "range_dialog",
                "<html><head/><body><p>Enter scan numbers as comma separated list. Ranges can be include using a dash (or minus symbol).</p><p><br/></p><p>The files will be found using the DLS info and the directories of any scan files already added</p><p><br/></p></body></html>",
            )
        )
